name: Sync to Hugging Face Space
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}            # your HF token (WRITE)
          HF_ACTOR: Mourya0402                 # <-- your personal HF username (NOT Team-13)
          HF_SPACE_SLUG: Team-13/scan_for_allergies    # <-- your Space slug
          SPACE_BRANCH: main
        run: |
          set -e
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git push "https://${HF_ACTOR}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE_SLUG}" HEAD:${SPACE_BRANCH}
